# Configuration for single-GPU training using accelerate
name: "Real_HAT_SRx4_mse_model_single_gpu"
model: 
  name: "Real_HAT"
  scale: 4
  pretrained_model: "path_to_pretrained_model"
dataset:
  train: 
    name: "train_dataset"
    path: "path_to_train_dataset"
  val: 
    name: "val_dataset"
    path: "path_to_val_dataset"
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.0001
  optimizer: 
    name: "adam"
    betas: [0.9, 0.999]
    eps: 1e-8
accelerate:
  use_accelerate: true
  num_processes: 1
  mixed_precision: "fp16"
