# Configuration for multi-GPU training using accelerate
name: "HAT-L_SRx3_ImageNet_from_scratch_multi_gpu"
model:
  name: "HAT-L"
  scale: 3
  init: "scratch"
dataset:
  name: "ImageNet"
  type: "train"
  path: "/path/to/imagenet/train"
  resolution: 256
  augmentations: true
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.0001
  optimizer: "adam"
  loss: "mse"
  scheduler: "cosine"
  accelerator: "multi_gpu"
  num_processes: 1
  num_machines: 1
  machine_rank: 0
  main_process_ip: "127.0.0.1"
  main_process_port: 29500
validation:
  dataset:
    name: "ImageNet"
    type: "val"
    path: "/path/to/imagenet/val"
    resolution: 256
  batch_size: 16
  metrics: ["psnr", "ssim"]
logging:
  interval: 10
  save_checkpoint: true
  checkpoint_interval: 5
  output_dir: "/path/to/output"
